### ISSUE TITLE
test case does not compile under OSX

### ISSUE THREAD

**Issue by hickst** [nfaction/vulnerabilities#1]
[twelf:vulnerabilities (master) 911] => ./ghost.sh
Running test against GHOST vulnerability
ghosttest.c:28:14: warning: implicit declaration of function 'gethostbyname_r' is invalid in C99
      [-Wimplicit-function-declaration]
    retval = gethostbyname_r(name, &resbuf, temp.buffer, sizeof(temp.buffer), &result, &herrno);
             ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_gethostbyname_r", referenced from:
      _main in ghosttest-f92c51.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
./ghost.sh: line 7: ./ghosttest: No such file or directory

**Comment by nfaction** [comment]
I noticed that this was the case as well.  I tried on my Mac, and same results.  Since the Mac OSX patch had so many fixes, I just recommend that any Mac user update immediately. Since information on GHOST for Mac just came out yesterday, there weren't any tests to run, but I will add them if I see any.  Thank you for the note though.

**Comment by nfaction** [comment]
With some further research, it appears that OSX was not vulnerable to GHOST directly, but this latest update contained a large amount of security patches that were critical anyhow.  I will not post any code as this link shows why OSX is not vulnerable: http://security.stackexchange.com/questions/80290/does-the-ghost-vulnerability-affect-macs
